<a href="https://colab.research.google.com/github/djcustard/GestureGAN/blob/master/ReshapeTheNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pickle
import os
import tensorflow as tf
import numpy as np


In [0]:
from google.colab import drive
data = '/content/drive/My Drive/Dataset'
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [0]:
print(os.listdir(data))

['AudioClips', 'MelSpecs', 'CSVs', 'ResizedData', 'ResizedData.npy']


In [0]:
melData = data+'/MelSpecs'
print(os.listdir(melData))

['mels_test.pkl', 'mels_train_curated.pkl', 'mels_train_noisy.pkl.zip', 'mels_trn_noisy_best50s.pkl']


In [0]:
mels_train_curated = melData+'/mels_train_curated.pkl'
unpik = open(mels_train_curated,"rb")
mel_train_curated = pickle.load(unpik)
total = len(mel_train_curated)
total

4970

In [0]:
test_spec = mel_train_curated[4969]
test_spec.shape

(128, 1769, 3)

In [0]:
print(test_spec)

In [0]:
resizedData = data+'/ResizedData/Spec'
index = 0
while index < (total-1):
  needed = mel_train_curated[index]
  theNew = np.resize(needed, (128,128,3))
  rD = resizedData+str(index)
  np.save(rD, theNew)
  print(index)
  index += 1

CODE WAS RUN TO SHOW THE DEVELOPMENT AS EACH NUMPY ARRAY WAS SHORTENED

In [0]:
newpath = os.listdir(data+'/ResizedData')
len(newpath)

4969

In [0]:
import random
nump = resizedData+str(random.randint(1,4969))+'.npy'
nplo = np.load(nump)
print(nplo)
nplo.shape

[[[34 34 34]
  [38 38 38]
  [53 53 53]
  ...
  [80 80 80]
  [58 58 58]
  [67 67 67]]

 [[55 55 55]
  [60 60 60]
  [71 71 71]
  ...
  [60 60 60]
  [67 67 67]
  [61 61 61]]

 [[64 64 64]
  [62 62 62]
  [71 71 71]
  ...
  [63 63 63]
  [76 76 76]
  [74 74 74]]

 ...

 [[ 2  2  2]
  [13 13 13]
  [ 7  7  7]
  ...
  [76 76 76]
  [66 66 66]
  [39 39 39]]

 [[28 28 28]
  [22 22 22]
  [ 0  0  0]
  ...
  [20 20 20]
  [15 15 15]
  [ 9  9  9]]

 [[ 0  0  0]
  [15 15 15]
  [10 10 10]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]


(128, 128, 3)